ref:
  index: /secondary/projects/bbc/research/STEM_20200803_WGBS/rn6/rn6.fa # this does not need to be different from config["ref"]["fasta"], but might be useful if 2-bit packed reference doesn't have .fa
  fasta: /secondary/projects/bbc/research/STEM_20200803_WGBS/rn6/rn6.fa
  assets: /secondary/projects/bbc/research/STEM_20200803_WGBS/rn6_biscuit_assets/

trim_galore:
   q: 30 #  Trim low-quality ends from reads in addition to adapter removal. Default phred score is 20
biscuit:
   lib_type: 0 # biscuit -b option (for strandedness)
   
sam_header: #
   PL: il
   PU: nova
   LB: b1
   
envmodules: # e.g. module load bbc/samtools/samtools-1.9
   samtools: bbc/samtools/samtools-1.9
   R: bbc/R/R-3.6.0
   snakemake: bbc/snakemake/snakemake-5.20.1
   trim_galore: bbc/trim_galore/trim_galore-0.6.0
   biscuit: bbc/biscuit/biscuit_0_3_16
   samblaster: bbc/samblaster/samblaster-0.1.24
   htslib: bbc/htslib/htslib-1.10.2
   bedtools: bbc/bedtools/bedtools-2.29.2
   fastqc: bbc/fastqc/fastqc-0.11.9
   multiqc: bbc/multiqc/multiqc-1.8
   parallel: bbc/parallel/parallel-20191122
