ref:
  index: /home/ian.beddows/canary/GRCh38_EMseq/EMseq_GRCh38.primary_assembly.genome.fa.gz # this does not need to be different from config["ref"]["fasta"], but might be useful if 2-bit packed reference doesn't have .fa
  fasta: /home/ian.beddows/canary/GRCh38_EMseq/EMseq_GRCh38.primary_assembly.genome.fa.gz
  assets: /home/ian.beddows/canary/GRCh38_EMseq/hg38/

trim_galore:
   q: 30 #  Trim low-quality ends from reads in addition to adapter removal. Default phred score is 20
biscuit:
   lib_type: 0 # biscuit -b option (for strandedness)

control_vectors: 1 # turn to 1 if this is an EMseq & was mapped to a genome including the control vectors with fasta headers ^J02459.1 (lamdba) and ^M77789.2 (puc19)
   
sam_header: #
   PL: il
   PU: nova
   LB: b1
   
envmodules: # e.g. module load bbc/samtools/samtools-1.9
   samtools: bbc/samtools/samtools-1.9
   R: bbc/R/R-3.6.0
   snakemake: bbc/snakemake/snakemake-5.28.0
   trim_galore: bbc/trim_galore/trim_galore-0.6.0
   biscuit: bbc/biscuit/biscuit_0_3_16
   samblaster: bbc/samblaster/samblaster-0.1.24
   htslib: bbc/htslib/htslib-1.10.2
   bedtools: bbc/bedtools/bedtools-2.29.2
   fastqc: bbc/fastqc/fastqc-0.11.9
   multiqc: bbc/multiqc/multiqc-1.9
   parallel: bbc/parallel/parallel-20191122
   pigz: bbc/pigz/pigz-2.4

hpcParameters:
   maxThreads: 32
   maxMemoryGb: 350
   trimThreads: 8
